@startuml

Class Event

Class Conference

Class BoardMeeting


(BoardMeeting, Conference) --|> Event

Class BoardMember

Class Member

Class Person

BoardMember --|> Member

Member --|> Person


Class Location

Class AAUOC


Location "1" -- "0..*" Event : isLocated In

Location "0..*" --o AAUOC

Event "0..*" -- "0..*" Member : attendsTo

BoardMeeting "0..*" -- "0..*" BoardMember : attendsTo

Conference "0..*" -- "0..*" Person : attendsTo

Event "0..*" --o AAUOC

Person "0..*" --o AAUOC

@enduml
